feat: add footer
tavomak/estela-website pull request #2
Opened 2024-12-17 20:05 UTC by cesarmartinez-estela

### Figma: 
![image](https://github.com/user-attachments/assets/076d2888-7eae-4a18-bdba-0d4e8df281dc)
![image](https://github.com/user-attachments/assets/6d79b566-dd4a-4df9-86b2-3623640949e6)

### Resultado:

![image](https://github.com/user-attachments/assets/7412e916-4de7-48a9-b409-4fee1966b5d7)
![image](https://github.com/user-attachments/assets/c23d5d54-5df3-45eb-be39-7071f9804857)

2024-12-18 21:54 UTC, tavomak requested changes

2024-12-18 21:54 UTC, tavomak commented on .gitignore
> +.env
No necesitas agregar esto, renombra tu archivo .env a .env.local

2024-12-18 21:54 UTC, tavomak commented on components/Atoms/Svg/EstelaIcon/EstelaLogo.tsx
> +const EstelaIcon = () => (
El componente y el archivo deberían tener el mismo nombre, en este caso EstelaLogo. Deberíamos usar mejores nombres algo cómo BrandLogoHorizontal, vertical, etc.

2024-12-18 21:54 UTC, tavomak commented on components/Atoms/Svg/EstelaIcon/EstelaLogo.tsx
> +          fill="white"
¿Esto no debería ser currentColor también?

2024-12-18 21:54 UTC, tavomak commented on components/Molecules/Footer/Footer.tsx
> +    <footer className="bg-ea-verde-oscuro text-white">
bg-ea-verde-oscuro debemos buscar mejores nombres para los colores!

2024-12-18 21:54 UTC, tavomak commented on components/Molecules/Footer/Footer.tsx
> +              Creamos vinculos duraderos
Todos los textos deben estar en el archivo de lenguaje.

2024-12-18 21:54 UTC, tavomak commented on components/Molecules/Footer/Footer.tsx
> +              ¡Conversemos!
Todos los textos deben estar en el archivo de lenguaje.

2024-12-18 21:54 UTC, tavomak commented on components/Molecules/Footer/Footer.tsx
> +          <Link
Esto debería abrir la modal con el formulario de contacto.

2024-12-18 21:54 UTC, tavomak commented on components/Molecules/Footer/Footer.tsx
> +            <p className="inline mr-2 lg:mr-0">Privacidad</p>
Todos los textos deben estar en el archivo de lenguaje.

2024-12-18 21:54 UTC, tavomak commented on components/Molecules/Footer/Footer.tsx
> +            <p className="inline">Términos y condiciones</p>
Todos los textos deben estar en el archivo de lenguaje.

2024-12-18 21:54 UTC, tavomak commented on components/Molecules/Footer/Footer.tsx
> +              Todos los derechos reservados
Todos los textos deben estar en el archivo de lenguaje.

2024-12-18 21:54 UTC, tavomak commented on components/Molecules/Footer/Footer.tsx
> +              <span className="text-ea-verde"> estela estudio digital</span>
Cambiar por una constante siteName

2024-12-18 21:54 UTC, tavomak commented on components/Molecules/Footer/Footer.tsx
> +            width={1088}
Chequea estos tamaños, en desktop veo que el tamaño máximo es 620X738

![image](https://github.com/user-attachments/assets/491ce7fb-4061-434f-bef1-cb8d30f697af)

2024-12-18 21:54 UTC, tavomak commented on components/Templates/Layout/Layout.tsx
>  // import Footer from 'components/Molecules/Footer';
Remover esta línea

2024-12-18 21:54 UTC, tavomak commented on package.json
> +  "packageManager": "pnpm@9.14.2+sha512.6e2baf77d06b9362294152c851c4f278ede37ab1eba3a55fda317a4a17b209f4dbb973fb250a77abc463a341fcb1f17f17cfa24091c4eb319cda0d9b84278387"
Cambiar por: "^pnpm@9.14.2"

2024-12-18 21:54 UTC, tavomak commented on pages/_document.tsx
> +      <body>
Está bien remover el background color acá pero debe ser añadido en el Layout className

2024-12-21 00:35 UTC, cesarmartinez-estela commented on package.json
> +  "packageManager": "pnpm@9.14.2+sha512.6e2baf77d06b9362294152c851c4f278ede37ab1eba3a55fda317a4a17b209f4dbb973fb250a77abc463a341fcb1f17f17cfa24091c4eb319cda0d9b84278387"
Lo hago de dos formas pero me lanza el mismo error:

![image](https://github.com/user-attachments/assets/5f73aa8e-a067-4329-bad1-ee1eff25c6c3)

![image](https://github.com/user-attachments/assets/8c88cc74-3a70-476e-9960-d5d9fe4708ca)

2024-12-21 00:50 UTC, cesarmartinez-estela commented on pages/_document.tsx
> +      <body>
Tengo una duda sobre eso, por qué le debemos colocar ese bg? En el figma la mayoria de fondos son blancos

2024-12-21 03:51 UTC, cesarmartinez-estela commented
### Navbar mobile 
**Se ven verde porque esta aplicado el activeItem, cuando hayan más rutas funcionará como en el figma**

![image](https://github.com/user-attachments/assets/70a38748-0027-41a2-a6f1-6fe46c3748f0)
![image](https://github.com/user-attachments/assets/abb8cd83-2370-41a2-8041-3234f51f9226)

### Navbar desktop
**Se ve el borde verde abajo porque esta aplicado el activeItem, cuando hayan más rutas funcionará como en el figma**

2024-12-30 09:10 UTC, cesarmartinez-estela commented
En el ultimo push de la PR, se ve realizada la maquetación de la homepage, mañana le agrego funcionalidad con hygragh y traducción, además de componetizar bien lo necesario. 

Me tome la libertad de crear algunas animaciones y ajustar ciertas cosas del diseño en figma en pro de mejores resultados.

2025-01-09 09:00 UTC, CisorM commented
En el ultimo push de la PR, componetice ciertos elementos que se repetían para reducir las líneas de código.

2025-06-20 02:20 UTC, merged

2025-06-20 02:21 UTC, tavomak commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/tavomak/estela-website/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: